# Term Exam Review: Python and Pandas

## Class Review

### Assessment overview
- **Exam time limit:** 60 minutes
- **Exam format:** 45 multiple-choice questions
- **Average exam pace:** about **1 minute 20 seconds per question**
- **Topics:**
  1. Introduction to Programming Using Python
  2. Programming with Numbers and Strings
  3. Loops / conditional statements
  4. Introduction to Pandas
  5. Data Cleaning and Preparation with Pandas
  6. Data Wrangling with Pandas

> **Class purpose:** This session reviews the main concepts, provides students with opportunities to predict code output, and offers guided and independent practice. It does not reproduce exam questions.

## Class Agenda: 100 Minutes

| Time | Topic and activity |
|---:|---|
| **0–5 min** | Welcome, exam format, and review strategy |
| **5–15 min** | Introduction to Python: variables, data types, and operators |
| **15–25 min** | Numbers and strings |
| **25–40 min** | Loops and code tracing |
| **40–55 min** | Introduction to pandas |
| **55–75 min** | Data cleaning and preparation with pandas |
| **75–90 min** | Data wrangling with pandas |
| **90–98 min** | Mixed multiple-choice practice |
| **98–100 min** | Final checklist and questions |

### Suggested delivery pattern
For each topic:
1. **Review** the key concepts.
2. **Predict** the result before running code.
3. **Run and discuss** the example.
4. **Try** the short “Your Turn” questions.

## 0–5 Minutes: Exam Format and Review Strategy

### Suggested exam approach
1. Complete straightforward questions first.
2. Mark uncertain questions and return to them.
3. For code questions, trace variables one line at a time.
4. Check details such as indentation, brackets, quotation marks, column names, and data types.
5. Reserve the final few minutes to review unanswered or flagged questions.

### Opening discussion
- Which topic feels most comfortable?
- Which topic needs the most review?
- What details are easy to overlook when reading code?

# 5–15 Minutes: Introduction to Programming Using Python

**Class focus:** Brief concept review, followed by operator-output predictions.

## Core ideas
- A **variable** stores a value and is created with `=`.
- Common data types include `int`, `float`, `str`, and `bool`.
- `type(value)` returns the value's data type.
- `print()` displays output.
- `input()` returns user input as a **string**.
- Python is case-sensitive: `score` and `Score` are different names.
- Comments begin with `#`.

## Common operators
- Arithmetic: `+`, `-`, `*`, `/`, `//`, `%`, `**`
- Comparison: `==`, `!=`, `<`, `<=`, `>`, `>=`
- Logical: `and`, `or`, `not`

In [6]:
age = 20
price = 12.50
course = "Python"
is_ready = True

print(type(age))
print(type(price))
print(type(course))
print(type(is_ready))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

### Predict the output
What will each expression return?

```python
10 / 4
10 // 4
10 % 4
2 ** 3
```

<details><summary>Show answers</summary>

- `10 / 4` → `2.5`
- `10 // 4` → `2`
- `10 % 4` → `2`
- `2 ** 3` → `8`

</details>

### Your Turn
1. Which operator tests whether two values are equal?
2. What data type is returned by `input()`?
3. What is the difference between `=` and `==`?

<details><summary>Show answers</summary>

1. `==`
2. `str`
3. `=` assigns a value; `==` compares two values.

</details>

# 15–25 Minutes: Programming with Numbers and Strings

**Class focus:** Type conversion, indexing, slicing, string methods, and formatted output.

## Numbers
- `int` represents whole numbers.
- `float` represents numbers with decimals.
- Use `int()`, `float()`, and `str()` for type conversion.
- Be careful when converting text that is not numeric.

## Strings
- Strings are enclosed in single or double quotation marks.
- Indexing starts at `0`.
- Negative indexing starts from the end: `-1` is the last character.
- Slicing uses `text[start:stop]`; the stop position is excluded.
- Useful methods include `.lower()`, `.upper()`, `.strip()`, `.replace()`, and `.split()`.
- f-strings insert values into text: `f"Name: {name}"`.

In [9]:
name = "  Data Analytics  "
clean_name = name.strip()

print(clean_name)
print(clean_name.lower())
print(clean_name[0])
print(clean_name[-1])
print(clean_name[0:4])

Data Analytics
data analytics
D
s
Data

### Predict the output
```python
x = "Python"
print(x[1])
print(x[1:4])
print(len(x))
```

<details><summary>Show answers</summary>

- `y`
- `yth`
- `6`

</details>

In [11]:
quantity = 3
price = 5.50
total = quantity * price
print(f"Total: ${total:.2f}")

Total: $16.50

### Your Turn
1. What is the result of `int("12") + 3`?
2. What does `.strip()` remove?
3. For `word = "Pandas"`, what is `word[-1]`?

<details><summary>Show answers</summary>

1. `15`
2. Leading and trailing whitespace.
3. `'s'`

</details>

# 25–40 Minutes: Loops

**Class focus:** Trace each loop by hand before executing it. Ask students to identify the changing variable and stopping condition.

## `for` loops
Use a `for` loop to repeat once for each item in a sequence.

## `while` loops
Use a `while` loop while a condition remains `True`. Make sure something eventually changes the condition to avoid an infinite loop.

## Important keywords
- `range(start, stop, step)` generates integer values; `stop` is excluded.
- `break` exits the loop.
- `continue` skips to the next iteration.
- An **accumulator** stores a running result, such as a total.

In [13]:
for number in range(1, 5):
    print(number)

1
2
3
4

In [2]:
total = 0
for number in [2, 4, 6]:
    total += number
    #total = number + total
print(total)

12

In [17]:
count = 3
while count > 0:
    print(count)
    count -= 1

3
2
1

In [ ]:
## This is an infinite loop. PLEASE DO NOT EXECUTE.
count = 3
while count > 0:
    print(count)
    count += 1

### Trace the loop
```python
total = 0
for i in range(3):
    total = total + i
print(total)
```

<details><summary>Show answer</summary>

`range(3)` produces `0, 1, 2`. The final value of `total` is `3`.

</details>

### Common mistakes
- Incorrect indentation
- Expecting the stop value from `range()` to be included
- Forgetting to initialize an accumulator
- Creating an infinite `while` loop
- Changing the wrong variable inside a loop

### Your Turn
1. What values are produced by `range(2, 8, 2)`?
2. Which statement immediately exits a loop?
3. How many times does `for i in range(5)` execute?

<details><summary>Show answers</summary>

1. `2, 4, 6`
2. `break`
3. Five times

</details>

## Mid-Class Checkpoint

Before moving into pandas, ask students to explain these ideas to a partner:

1. The difference between `=` and `==`
2. The difference between `/`, `//`, and `%`
3. Why the stop value in `range()` is not included
4. How a `while` loop can become infinite

**Instructor check:** Address one or two common misunderstandings, then continue to pandas.

# 40–55 Minutes: Introduction to Pandas

**Class focus:** Create and inspect a DataFrame, then practise selecting columns and filtering rows.

## Core objects
- A **Series** is one-dimensional.
- A **DataFrame** is a two-dimensional table with rows and columns.
- Import pandas with `import pandas as pd`.
- Read a CSV file with `pd.read_csv()`.

## Essential inspection tools
- `.head()` and `.tail()` preview rows.
- `.shape` gives `(rows, columns)`.
- `.columns` lists column names.
- `.dtypes` shows each column's data type.
- `.info()` summarizes structure, non-null counts, and data types.
- `.describe()` summarizes numeric columns by default.

In [19]:
import pandas as pd

students = pd.DataFrame({
    "name": ["Ava", "Ben", "Chen", "Dina"],
    "score": [82, 74, 91, 88],
    "program": ["DMIT", "DMIT", "BAIST", "BAIST"]
})

students

   name  score program
0   Ava     82    DMIT
1   Ben     74    DMIT
2  Chen     91   BAIST
3  Dina     88   BAIST

In [21]:
print(students.shape)
print(students.columns)
print(students.dtypes)
students.head()

(4, 3)
Index(['name', 'score', 'program'], dtype='object')
name       object
score       int64
program    object
dtype: object

   name  score program
0   Ava     82    DMIT
1   Ben     74    DMIT
2  Chen     91   BAIST
3  Dina     88   BAIST

## Selecting data
- One column as a Series: `df["column"]`
- Multiple columns as a DataFrame: `df[["col1", "col2"]]`
- Label-based selection: `.loc[]`
- Position-based selection: `.iloc[]`
- Filter rows with a Boolean condition.

In [24]:
students["score"]

0    82
1    74
2    91
3    88
Name: score, dtype: int64

In [26]:
students[["name", "score"]]

   name  score
0   Ava     82
1   Ben     74
2  Chen     91
3  Dina     88

In [28]:
students.loc[students["score"] >= 85, ["name", "score"]]

   name  score
2  Chen     91
3  Dina     88

### Your Turn
1. Which attribute returns the number of rows and columns?
2. Which method previews the first five rows by default?
3. Which selector is based on integer position?

<details><summary>Show answers</summary>

1. `.shape`
2. `.head()`
3. `.iloc[]`

</details>

# 55–75 Minutes: Data Cleaning and Preparation with Pandas

**Class focus:** Spend extra time distinguishing true missing values from invalid placeholders such as `?`.

## Missing and invalid values
- `NaN` represents a missing value in many pandas operations.
- `.isna()` or `.isnull()` detects missing values.
- `.notna()` detects non-missing values.
- `.dropna()` removes rows or columns containing missing values.
- `.fillna()` replaces missing values.
- A placeholder such as `?`, `N/A`, or `unknown` may be stored as ordinary text unless it is converted or identified when reading the data.

> **Key distinction:** A missing value and an invalid placeholder are not automatically the same thing.

In [30]:
dirty = pd.DataFrame({
    "name": [" Ava ", "Ben", "Chen", "Ben"],
    "age": [20, None, "?", None],
    "city": ["Edmonton", "edmonton", "Calgary", "edmonton"]
})

dirty

    name   age      city
0   Ava     20  Edmonton
1    Ben  None  edmonton
2   Chen     ?   Calgary
3    Ben  None  edmonton

In [32]:
# Replace the invalid placeholder with a true missing value
clean = dirty.replace("?", pd.NA)

# Standardize text
clean["name"] = clean["name"].str.strip()
clean["city"] = clean["city"].str.title()

clean

   name   age      city
0   Ava    20  Edmonton
1   Ben  None  Edmonton
2  Chen  <NA>   Calgary
3   Ben  None  Edmonton

In [34]:
# Count missing values by column
clean.isna().sum()

name    0
age     3
city    0
dtype: int64

In [36]:
# Convert age to a numeric data type; invalid values become NaN
clean["age"] = pd.to_numeric(clean["age"], errors="coerce")
clean.dtypes

name     object
age     float64
city     object
dtype: object

In [38]:
# Find and remove duplicate rows
print(clean.duplicated().sum())
clean_no_duplicates = clean.drop_duplicates()
clean_no_duplicates

1

   name   age      city
0   Ava  20.0  Edmonton
1   Ben   NaN  Edmonton
2  Chen   NaN   Calgary

## Common cleaning operations
- Rename columns: `df.rename(columns={"old": "new"})`
- Change data type: `.astype()` or `pd.to_numeric()`
- Replace values: `.replace()`
- Standardize strings: `.str.strip()`, `.str.lower()`, `.str.upper()`, `.str.title()`
- Detect duplicates: `.duplicated()`
- Remove duplicates: `.drop_duplicates()`

### Your Turn
1. Why might `df.info()` show no missing values even when a column contains `?`?
2. Which expression counts missing values in every column?
3. What does `errors="coerce"` do in `pd.to_numeric()`?

<details><summary>Show answers</summary>

1. `?` may be an ordinary string, not a recognized missing value.
2. `df.isna().sum()`
3. It converts values that cannot be parsed as numbers to `NaN`.

</details>

# 75–90 Minutes: Data Wrangling with Pandas

**Class focus:** Connect each operation to a business question: filter, sort, summarize, combine, or reshape.

Data wrangling means reshaping, combining, filtering, sorting, summarizing, and transforming data for analysis.

## Common operations
- Sort: `.sort_values()`
- Filter: Boolean conditions
- Create a column: `df["new"] = ...`
- Group and summarize: `.groupby().agg()`
- Combine tables by a key: `pd.merge()`
- Stack tables: `pd.concat()`
- Reshape summaries: `.pivot_table()`

In [41]:
sales = pd.DataFrame({
    "region": ["North", "North", "South", "South"],
    "product": ["Coffee", "Tea", "Coffee", "Tea"],
    "units": [10, 8, 12, 7],
    "price": [4.0, 3.0, 4.0, 3.0]
})

sales["revenue"] = sales["units"] * sales["price"]
sales

  region product  units  price  revenue
0  North  Coffee     10    4.0     40.0
1  North     Tea      8    3.0     24.0
2  South  Coffee     12    4.0     48.0
3  South     Tea      7    3.0     21.0

In [43]:
# Sort from highest to lowest revenue
sales.sort_values("revenue", ascending=False)

  region product  units  price  revenue
2  South  Coffee     12    4.0     48.0
0  North  Coffee     10    4.0     40.0
1  North     Tea      8    3.0     24.0
3  South     Tea      7    3.0     21.0

In [45]:
# Group and summarize
sales.groupby("region", as_index=False).agg(
    total_units=("units", "sum"),
    total_revenue=("revenue", "sum")
)

  region  total_units  total_revenue
0  North           18           64.0
1  South           19           69.0

In [47]:
# Filter with two conditions; use parentheses around each condition
sales[(sales["region"] == "South") & (sales["units"] >= 10)]

  region product  units  price  revenue
2  South  Coffee     12    4.0     48.0

In [49]:
products = pd.DataFrame({
    "product": ["Coffee", "Tea"],
    "category": ["Hot Drink", "Hot Drink"]
})

pd.merge(sales, products, on="product", how="left")

  region product  units  price  revenue   category
0  North  Coffee     10    4.0     40.0  Hot Drink
1  North     Tea      8    3.0     24.0  Hot Drink
2  South  Coffee     12    4.0     48.0  Hot Drink
3  South     Tea      7    3.0     21.0  Hot Drink

In [51]:
sales.pivot_table(
    index="region",
    columns="product",
    values="revenue",
    aggfunc="sum"
)

product  Coffee   Tea
region
North      40.0  24.0
South      48.0  21.0

### `merge` versus `concat`
- Use `merge` to combine tables using matching key columns.
- Use `concat` to stack or align objects along rows or columns.

### Your Turn
1. Which operation summarizes values for categories?
2. Which function combines tables using a shared key?
3. Why are parentheses important in a filter with `&` or `|`?

<details><summary>Show answers</summary>

1. `.groupby()` followed by an aggregation such as `.sum()` or `.mean()`
2. `pd.merge()`
3. They clearly separate each Boolean condition and ensure the expression is evaluated correctly.

</details>

# 90–98 Minutes: Mixed Multiple-Choice Practice

**Activity:** Give students about five minutes to answer independently, then use the remaining time to review the answers and reasoning.

Try these without running code first.

### 1. What is the result of `7 // 2`?
A. `3.5`  
B. `3`  
C. `1`  
D. `4`

### 2. Which method removes whitespace from both ends of a string?
A. `.split()`  
B. `.replace()`  
C. `.strip()`  
D. `.remove()`

### 3. How many values are produced by `range(1, 5)`?
A. 3  
B. 4  
C. 5  
D. 6

### 4. Which expression selects two DataFrame columns?
A. `df["a", "b"]`  
B. `df["a" and "b"]`  
C. `df[["a", "b"]]`  
D. `df("a", "b")`

### 5. Which expression counts missing values by column?
A. `df.info()`  
B. `df.isna().sum()`  
C. `df.nulls()`  
D. `df.dropna()`

### 6. Which operation is most appropriate for calculating average sales by region?
A. `.head()`  
B. `.rename()`  
C. `.groupby()` with `.mean()`  
D. `.drop_duplicates()`

### 7. What does `pd.to_numeric(series, errors="coerce")` do to invalid numeric text?
A. Deletes the whole DataFrame  
B. Leaves all values unchanged  
C. Converts invalid values to `NaN`  
D. Converts all values to strings

### 8. Which keyword skips the remainder of the current loop iteration?
A. `break`  
B. `continue`  
C. `stop`  
D. `passout`

<details><summary>Show answer key</summary>

1. B  
2. C  
3. B  
4. C  
5. B  
6. C  
7. C  
8. B

</details>

# 98–100 Minutes: Final Checklist and Wrap-Up

Before the exam, make sure you can:

- [ ] Identify Python data types and operators.
- [ ] Trace variable assignment and expressions.
- [ ] Index, slice, format, and clean strings.
- [ ] Trace `for` and `while` loops.
- [ ] Explain `range()` and use an accumulator.
- [ ] Create and inspect a pandas DataFrame.
- [ ] Select columns and filter rows.
- [ ] Distinguish missing values from invalid placeholders.
- [ ] Clean strings, convert data types, and handle duplicates.
- [ ] Sort, group, aggregate, merge, concatenate, and pivot data.
- [ ] Read code carefully without relying only on execution.

## One-page memory cues
- Assignment: `=` | Comparison: `==`
- Division: `/` | Floor division: `//` | Remainder: `%`
- String position begins at `0`; slice stop is excluded.
- `range()` excludes its stop value.
- `df["col"]` → Series; `df[["col"]]` → DataFrame.
- `.loc[]` uses labels; `.iloc[]` uses positions.
- `?` may be invalid text rather than a missing value.
- `&` means element-wise AND; `|` means element-wise OR in pandas filters.
- `merge` joins by keys; `concat` stacks or aligns objects.

## Exit Ticket

Before leaving, write down:

1. **One concept you can now explain confidently**
2. **One pandas operation you need to practise again**
3. **One code-reading mistake you will watch for during the exam**

> Use the checklist above to guide your final independent review.